// packages/react/src/components/Comment.tsx
import { useState } from 'react';
import { formatTimestamp } from '@threadkit/core';
import type { CommentProps } from '../types';
import { CommentForm } from './CommentForm';
import { UserHoverCard } from './UserHoverCard';
import { renderMarkdown } from '../utils/markdown';
import { useTranslation } from '../i18n';

type ReportReasonKey = 'reportSpam' | 'reportHarassment' | 'reportHateSpeech' | 'reportMisinformation' | 'reportOther';
const REPORT_REASON_KEYS: ReportReasonKey[] = [
  'reportSpam',
  'reportHarassment',
  'reportHateSpeech',
  'reportMisinformation',
  'reportOther',
];

export function Comment({
  comment,
  currentUser,
  depth = 0,
  maxDepth = 5,
  collapsed: initialCollapsed = false,
  highlighted = false,
  index = 0,
  totalSiblings = 1,
  highlightedCommentId,
  collapsedThreads,
  onPost,
  onReply,
  onVote,
  onDelete,
  onEdit,
  onBan,
  onBlock,
  onReport,
  onPermalink,
  onPrev,
  onNext,
  onCollapse,
  getUserProfile,
  plugins,
}: CommentProps) {
  const t = useTranslation();
  const [showReplyForm, setShowReplyForm] = useState(false);
  const [collapsed, setCollapsed] = useState(initialCollapsed);
  const [confirmingAction, setConfirmingAction] = useState<'block' | 'delete' | 'ban' | null>(null);
  const [showReportForm, setShowReportForm] = useState(false);
  const [reportReason, setReportReason] = useState<string>('');
  const [reportSubmitted, setReportSubmitted] = useState(false);
  const [isEditing, setIsEditing] = useState(false);
  const [editText, setEditText] = useState(comment.text);

  const upvotes = comment.upvotes.length;
  const downvotes = comment.downvotes.length;
  const score = upvotes - downvotes;
  const hasUpvoted = currentUser && comment.upvotes.includes(currentUser.id);
  const hasDownvoted = currentUser && comment.downvotes.includes(currentUser.id);
  const isModOrAdmin = currentUser?.isModerator || currentUser?.isAdmin;
  const isOwnComment = currentUser && comment.userId === currentUser.id;
  // Deleted comments have a special userId starting with 'd' and all zeros
  const isDeleted = comment.status === 'deleted' || comment.userId === 'd0000000-0000-0000-0000-000000000000';

  const handleReply = async (text: string, parentId?: string) => {
    if (onPost) {
      await onPost(text, parentId);
    }
    onReply?.(comment.id);
    setShowReplyForm(false);
  };

  const handleCollapse = () => {
    setCollapsed(!collapsed);
    onCollapse?.(comment.id);
  };

  const handleSaveEdit = () => {
    if (editText.trim() && editText !== comment.text) {
      onEdit?.(comment.id, editText.trim());
    }
    setIsEditing(false);
  };

  const handleCancelEdit = () => {
    setEditText(comment.text);
    setIsEditing(false);
  };

  const commentClassName = `threadkit-comment${highlighted ? ' threadkit-highlighted' : ''}${isDeleted ? ' threadkit-deleted' : ''}`;

  if (collapsed) {
    return (
      <div className={`${commentClassName} threadkit-comment-collapsed`} data-comment-id={comment.id}>
        <button
          className="threadkit-expand-btn"
          onClick={handleCollapse}
          title={t('expandComment')}
        >
          [+]
        </button>
        <UserHoverCard
          userName={comment.userName}
          userId={comment.userId}
          getUserProfile={getUserProfile}
        >
          <span className="threadkit-author">{comment.userName}</span>
        </UserHoverCard>
        <span className="threadkit-collapsed-info">
          {score} {score !== 1 ? t('points') : t('point')} · {formatTimestamp(comment.timestamp)}
          {comment.children.length > 0 && ` · ${comment.children.length} ${comment.children.length === 1 ? t('child') : t('children')}`}
        </span>
      </div>
    );
  }

  return (
    <div className={commentClassName} data-comment-id={comment.id} id={`threadkit-${comment.id}`}>
      <div className="threadkit-comment-wrapper">
        {/* Vote column - hidden for deleted comments */}
        {onVote && !isDeleted && (
          <div className="threadkit-vote-column">
            <button
              className={`threadkit-vote-btn threadkit-vote-up ${hasUpvoted ? 'active' : ''}`}
              onClick={() => onVote(comment.id, 'up')}
              aria-label={t('upvote')}
            >
              ▲
            </button>
            <button
              className={`threadkit-vote-btn threadkit-vote-down ${hasDownvoted ? 'active' : ''}`}
              onClick={() => onVote(comment.id, 'down')}
              aria-label={t('downvote')}
            >
              ▼
            </button>
          </div>
        )}

        {/* Content column */}
        <div className="threadkit-comment-content">
          {/* Header line */}
          <div className="threadkit-comment-header">
            <UserHoverCard
              userName={comment.userName}
              userId={comment.userId}
              getUserProfile={getUserProfile}
            >
              <span className="threadkit-author">{comment.userName}</span>
            </UserHoverCard>

            <span className="threadkit-score">
              {score} {score !== 1 ? t('points') : t('point')}
              <span className="threadkit-score-breakdown">
                (+{upvotes}/-{downvotes})
              </span>
            </span>

            <span className="threadkit-timestamp">
              {formatTimestamp(comment.timestamp)}
            </span>

            {comment.edited && <span className="threadkit-edited">*</span>}

            {comment.pinned && <span className="threadkit-pinned">{t('pinned')}</span>}

            <span className="threadkit-header-divider">|</span>

            {index > 0 && onPrev && (
              <button className="threadkit-nav-btn" onClick={onPrev}>
                {t('prev')}
              </button>
            )}

            {index < totalSiblings - 1 && onNext && (
              <button className="threadkit-nav-btn" onClick={onNext}>
                {t('next')}
              </button>
            )}

            <button
              className="threadkit-collapse-btn"
              onClick={handleCollapse}
              title={t('collapseComment')}
            >
              [–]
            </button>
          </div>

          {/* Comment body */}
          <div className="threadkit-comment-body">
            {isEditing ? (
              <div className="threadkit-edit-form">
                <textarea
                  className="threadkit-textarea"
                  value={editText}
                  onChange={(e) => setEditText(e.target.value)}
                  rows={4}
                  autoFocus
                />
                <div className="threadkit-edit-actions">
                  <button
                    className="threadkit-submit-btn"
                    onClick={handleSaveEdit}
                    disabled={!editText.trim()}
                  >
                    {t('save')}
                  </button>
                  <button
                    className="threadkit-cancel-btn"
                    onClick={handleCancelEdit}
                  >
                    {t('cancel')}
                  </button>
                </div>
              </div>
            ) : (
              renderMarkdown(comment.text, {
                allowLinks: true,
                enableAutoLinks: true,
                enableMentions: true,
                getUserProfile,
                plugins,
              })
            )}
          </div>

          {/* Action row - hidden for deleted comments */}
          {!isEditing && !isDeleted && (
            <div className="threadkit-comment-actions">
              {/* Share button - uses Web Share API when available, falls back to copy link */}
              <button
                className="threadkit-action-btn"
                onClick={async () => {
                  const url = `${window.location.origin}${window.location.pathname}#threadkit-${comment.id}`;
                  if (navigator.share) {
                    try {
                      await navigator.share({ url });
                    } catch {
                      // User cancelled or share failed, silently ignore
                    }
                  } else {
                    await navigator.clipboard.writeText(url);
                  }
                }}
              >
                {t('share')}
              </button>

              {/* Own comment actions: edit, reply, delete */}
              {isOwnComment ? (
                <>
                  {onEdit && (
                    <button
                      className="threadkit-action-btn"
                      onClick={() => setIsEditing(true)}
                    >
                      {t('edit')}
                    </button>
                  )}

                  {depth < maxDepth && (
                    <button
                      className="threadkit-action-btn"
                      onClick={() => setShowReplyForm(!showReplyForm)}
                    >
                      {t('reply')}
                    </button>
                  )}

                  {onDelete && (
                    confirmingAction === 'delete' ? (
                      <span className="threadkit-confirm-inline">
                        {t('deleteConfirm')}
                        <button
                          className="threadkit-confirm-btn threadkit-confirm-yes"
                          onClick={() => {
                            onDelete(comment.id);
                            setConfirmingAction(null);
                          }}
                        >
                          {t('yes')}
                        </button>
                        <button
                          className="threadkit-confirm-btn threadkit-confirm-no"
                          onClick={() => setConfirmingAction(null)}
                        >
                          {t('no')}
                        </button>
                      </span>
                    ) : (
                      <button
                        className="threadkit-action-btn"
                        onClick={() => setConfirmingAction('delete')}
                      >
                        {t('delete')}
                      </button>
                    )
                  )}
                </>
              ) : (
                <>
                  {/* Other user's comment actions: block, report, reply, (mod: delete, ban) */}
                  {currentUser && onBlock && (
                    confirmingAction === 'block' ? (
                      <span className="threadkit-confirm-inline">
                        {t('blockConfirm')}
                        <button
                          className="threadkit-confirm-btn threadkit-confirm-yes"
                          onClick={() => {
                            onBlock(comment.userId);
                            setConfirmingAction(null);
                          }}
                        >
                          {t('yes')}
                        </button>
                        <button
                          className="threadkit-confirm-btn threadkit-confirm-no"
                          onClick={() => setConfirmingAction(null)}
                        >
                          {t('no')}
                        </button>
                      </span>
                    ) : (
                      <button
                        className="threadkit-action-btn"
                        onClick={() => setConfirmingAction('block')}
                      >
                        {t('block')}
                      </button>
                    )
                  )}

                  {currentUser && onReport && (
                    reportSubmitted ? (
                      <span className="threadkit-report-thanks">{t('reportSubmitted')}</span>
                    ) : showReportForm ? (
                      <span className="threadkit-report-inline">
                        <select
                          className="threadkit-report-select"
                          value={reportReason}
                          onChange={(e) => setReportReason(e.target.value)}
                        >
                          <option value="">{t('selectReason')}</option>
                          {REPORT_REASON_KEYS.map((reasonKey) => (
                            <option key={reasonKey} value={reasonKey}>
                              {t(reasonKey)}
                            </option>
                          ))}
                        </select>
                        <button
                          className="threadkit-confirm-btn threadkit-confirm-yes"
                          disabled={!reportReason}
                          onClick={() => {
                            onReport(comment.id);
                            setShowReportForm(false);
                            setReportSubmitted(true);
                          }}
                        >
                          {t('submit')}
                        </button>
                        <button
                          className="threadkit-confirm-btn threadkit-confirm-no"
                          onClick={() => {
                            setShowReportForm(false);
                            setReportReason('');
                          }}
                        >
                          {t('cancel')}
                        </button>
                      </span>
                    ) : (
                      <button
                        className="threadkit-action-btn"
                        onClick={() => setShowReportForm(true)}
                      >
                        {t('report')}
                      </button>
                    )
                  )}

                  {depth < maxDepth && (
                    <button
                      className="threadkit-action-btn"
                      onClick={() => setShowReplyForm(!showReplyForm)}
                    >
                      {t('reply')}
                    </button>
                  )}

                  {isModOrAdmin && onDelete && (
                    confirmingAction === 'delete' ? (
                      <span className="threadkit-confirm-inline">
                        {t('deleteConfirm')}
                        <button
                          className="threadkit-confirm-btn threadkit-confirm-yes"
                          onClick={() => {
                            onDelete(comment.id);
                            setConfirmingAction(null);
                          }}
                        >
                          {t('yes')}
                        </button>
                        <button
                          className="threadkit-confirm-btn threadkit-confirm-no"
                          onClick={() => setConfirmingAction(null)}
                        >
                          {t('no')}
                        </button>
                      </span>
                    ) : (
                      <button
                        className="threadkit-action-btn threadkit-mod-action"
                        onClick={() => setConfirmingAction('delete')}
                      >
                        {t('delete')}
                      </button>
                    )
                  )}

                  {isModOrAdmin && onBan && (
                    confirmingAction === 'ban' ? (
                      <span className="threadkit-confirm-inline">
                        {t('banConfirm')}
                        <button
                          className="threadkit-confirm-btn threadkit-confirm-yes"
                          onClick={() => {
                            onBan(comment.userId);
                            setConfirmingAction(null);
                          }}
                        >
                          {t('yes')}
                        </button>
                        <button
                          className="threadkit-confirm-btn threadkit-confirm-no"
                          onClick={() => setConfirmingAction(null)}
                        >
                          {t('no')}
                        </button>
                      </span>
                    ) : (
                      <button
                        className="threadkit-action-btn threadkit-mod-action"
                        onClick={() => setConfirmingAction('ban')}
                      >
                        {t('ban')}
                      </button>
                    )
                  )}
                </>
              )}
            </div>
          )}

          {/* Reply form */}
          {showReplyForm && (
            <div className="threadkit-reply-form">
              <CommentForm
                parentId={comment.id}
                placeholder={t('writeReply')}
                autoFocus
                onSubmit={handleReply}
                onCancel={() => setShowReplyForm(false)}
              />
            </div>
          )}

          {/* Child comments */}
          {comment.children.length > 0 && (
            <div className="threadkit-replies">
              {comment.children.map((child, childIndex) => (
                <Comment
                  key={child.id}
                  comment={child}
                  currentUser={currentUser}
                  depth={depth + 1}
                  maxDepth={maxDepth}
                  index={childIndex}
                  totalSiblings={comment.children.length}
                  highlighted={highlightedCommentId === child.id}
                  collapsed={collapsedThreads?.has(child.id)}
                  highlightedCommentId={highlightedCommentId}
                  collapsedThreads={collapsedThreads}
                  onPost={onPost}
                  onReply={onReply}
                  onVote={onVote}
                  onDelete={onDelete}
                  onEdit={onEdit}
                  onBan={onBan}
                  onBlock={onBlock}
                  onReport={onReport}
                  onPermalink={onPermalink}
                  onCollapse={onCollapse}
                  getUserProfile={getUserProfile}
                  plugins={plugins}
                />
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

// packages/svelte/src/components/Comment.svelte
<script lang="ts">
  import type { Comment as CommentType, User, UserProfile, ThreadKitPlugin } from '@threadkit/core';
  import { renderMarkdown, formatTimestamp } from '../utils/markdown';
  import { getTranslation } from '../i18n';
  import CommentForm from './CommentForm.svelte';
  import UserHoverCard from './UserHoverCard.svelte';
  // Self-import for recursive rendering
  import Comment from './Comment.svelte';

  const t = getTranslation();

  type ReportReasonKey = 'reportSpam' | 'reportHarassment' | 'reportHateSpeech' | 'reportMisinformation' | 'reportOther';
  const REPORT_REASON_KEYS: ReportReasonKey[] = [
    'reportSpam',
    'reportHarassment',
    'reportHateSpeech',
    'reportMisinformation',
    'reportOther',
  ];

  interface Props {
    comment: CommentType;
    currentUser?: User;
    depth?: number;
    maxDepth?: number;
    collapsed?: boolean;
    highlighted?: boolean;
    index?: number;
    totalSiblings?: number;
    highlightedCommentId?: string | null;
    collapsedThreads?: Set<string>;
    onReply?: (commentId: string) => void;
    onVote?: (commentId: string, voteType: 'up' | 'down') => void;
    onDelete?: (commentId: string) => void;
    onEdit?: (commentId: string, newText: string) => void;
    onBan?: (userId: string) => void;
    onBlock?: (userId: string) => void;
    onReport?: (commentId: string) => void;
    onPermalink?: (commentId: string) => void;
    onPrev?: () => void;
    onNext?: () => void;
    onCollapse?: (commentId: string) => void;
    getUserProfile?: (userId: string) => UserProfile | undefined;
    plugins?: ThreadKitPlugin[];
  }

  let {
    comment,
    currentUser,
    depth = 0,
    maxDepth = 5,
    collapsed: initialCollapsed = false,
    highlighted = false,
    index = 0,
    totalSiblings = 1,
    highlightedCommentId,
    collapsedThreads,
    onReply,
    onVote,
    onDelete,
    onEdit,
    onBan,
    onBlock,
    onReport,
    onPermalink,
    onPrev,
    onNext,
    onCollapse,
    getUserProfile,
    plugins,
  }: Props = $props();

  let showReplyForm = $state(false);
  let collapsed = $derived(initialCollapsed);
  let localCollapsed = $state<boolean | null>(null);
  let confirmingAction = $state<'block' | 'delete' | 'ban' | null>(null);
  let showReportForm = $state(false);
  let reportReason = $state('');
  let reportSubmitted = $state(false);
  let isEditing = $state(false);
  let editText = $derived(comment.text);
  let localEditText = $state<string | null>(null);

  // Use local state if set, otherwise use prop
  const isCollapsed = $derived(localCollapsed !== null ? localCollapsed : collapsed);
  const currentEditText = $derived(localEditText !== null ? localEditText : editText);

  const upvotes = $derived(comment.upvotes.length);
  const downvotes = $derived(comment.downvotes.length);
  const score = $derived(upvotes - downvotes);
  const hasUpvoted = $derived(currentUser && comment.upvotes.includes(currentUser.id));
  const hasDownvoted = $derived(currentUser && comment.downvotes.includes(currentUser.id));
  const isModOrAdmin = $derived(currentUser?.isModerator || currentUser?.isAdmin);
  const isOwnComment = $derived(currentUser && comment.userId === currentUser.id);

  const parsedContent = $derived(renderMarkdown(comment.text, {
    allowLinks: true,
    enableAutoLinks: true,
    enableMentions: true,
    getUserProfile,
    plugins,
  }));

  function handleReply() {
    onReply?.(comment.id);
    showReplyForm = false;
  }

  function handleCollapse() {
    localCollapsed = !isCollapsed;
    onCollapse?.(comment.id);
  }

  function handleSaveEdit() {
    if (currentEditText.trim() && currentEditText !== comment.text) {
      onEdit?.(comment.id, currentEditText.trim());
    }
    isEditing = false;
    localEditText = null;
  }

  function handleCancelEdit() {
    localEditText = null;
    isEditing = false;
  }

  function handleEditTextChange(value: string) {
    localEditText = value;
  }

  function handleFormCancel() {
    showReplyForm = false;
  }
</script>

{#if isCollapsed}
  <div
    class="threadkit-comment threadkit-comment-collapsed"
    class:threadkit-highlighted={highlighted}
    data-comment-id={comment.id}
  >
    <button
      class="threadkit-expand-btn"
      onclick={handleCollapse}
      title={t('expandComment')}
    >
      [+]
    </button>
    <UserHoverCard
      userName={comment.userName}
      userId={comment.userId}
      {getUserProfile}
    >
      {#snippet children()}
        <span class="threadkit-author">{comment.userName}</span>
      {/snippet}
    </UserHoverCard>
    <span class="threadkit-collapsed-info">
      {score} {score !== 1 ? t('points') : t('point')} &middot; {formatTimestamp(comment.timestamp)}
      {#if comment.children.length > 0}
        &middot; {comment.children.length} {comment.children.length === 1 ? t('child') : t('children')}
      {/if}
    </span>
  </div>
{:else}
  <div
    class="threadkit-comment"
    class:threadkit-highlighted={highlighted}
    data-comment-id={comment.id}
    id="threadkit-{comment.id}"
  >
    <div class="threadkit-comment-wrapper">
      <!-- Vote column -->
      {#if onVote}
        <div class="threadkit-vote-column">
          <button
            class="threadkit-vote-btn threadkit-vote-up"
            class:active={hasUpvoted}
            onclick={() => onVote?.(comment.id, 'up')}
            aria-label={t('upvote')}
          >
            &#9650;
          </button>
          <button
            class="threadkit-vote-btn threadkit-vote-down"
            class:active={hasDownvoted}
            onclick={() => onVote?.(comment.id, 'down')}
            aria-label={t('downvote')}
          >
            &#9660;
          </button>
        </div>
      {/if}

      <!-- Content column -->
      <div class="threadkit-comment-content">
        <!-- Header line -->
        <div class="threadkit-comment-header">
          <UserHoverCard
            userName={comment.userName}
            userId={comment.userId}
            {getUserProfile}
          >
            {#snippet children()}
              <span class="threadkit-author">{comment.userName}</span>
            {/snippet}
          </UserHoverCard>

          <span class="threadkit-score">
            {score} {score !== 1 ? t('points') : t('point')}
            <span class="threadkit-score-breakdown">
              (+{upvotes}/-{downvotes})
            </span>
          </span>

          <span class="threadkit-timestamp">
            {formatTimestamp(comment.timestamp)}
          </span>

          {#if comment.edited}
            <span class="threadkit-edited">*</span>
          {/if}

          {#if comment.pinned}
            <span class="threadkit-pinned">{t('pinned')}</span>
          {/if}

          <span class="threadkit-header-divider">|</span>

          {#if index > 0 && onPrev}
            <button class="threadkit-nav-btn" onclick={onPrev}>
              {t('prev')}
            </button>
          {/if}

          {#if index < totalSiblings - 1 && onNext}
            <button class="threadkit-nav-btn" onclick={onNext}>
              {t('next')}
            </button>
          {/if}

          <button
            class="threadkit-collapse-btn"
            onclick={handleCollapse}
            title={t('collapseComment')}
          >
            [&ndash;]
          </button>
        </div>

        <!-- Comment body -->
        <div class="threadkit-comment-body">
          {#if isEditing}
            <div class="threadkit-edit-form">
              <textarea
                class="threadkit-textarea"
                value={currentEditText}
                oninput={(e) => handleEditTextChange((e.target as HTMLTextAreaElement).value)}
                rows={4}
              ></textarea>
              <div class="threadkit-edit-actions">
                <button
                  class="threadkit-submit-btn"
                  onclick={handleSaveEdit}
                  disabled={!currentEditText.trim()}
                >
                  {t('save')}
                </button>
                <button
                  class="threadkit-cancel-btn"
                  onclick={handleCancelEdit}
                >
                  {t('cancel')}
                </button>
              </div>
            </div>
          {:else}
            {@html parsedContent}
          {/if}
        </div>

        <!-- Action row -->
        {#if !isEditing}
          <div class="threadkit-comment-actions">
            <!-- Share button - uses Web Share API when available, falls back to copy link -->
            <button
              class="threadkit-action-btn"
              onclick={async () => {
                const url = `${window.location.origin}${window.location.pathname}#threadkit-${comment.id}`;
                if (navigator.share) {
                  try {
                    await navigator.share({ url });
                  } catch {
                    // User cancelled or share failed, silently ignore
                  }
                } else {
                  await navigator.clipboard.writeText(url);
                }
              }}
            >
              {t('share')}
            </button>

            <!-- Own comment actions: edit, reply, delete -->
            {#if isOwnComment}
              {#if onEdit}
                <button
                  class="threadkit-action-btn"
                  onclick={() => isEditing = true}
                >
                  {t('edit')}
                </button>
              {/if}

              {#if depth < maxDepth}
                <button
                  class="threadkit-action-btn"
                  onclick={() => showReplyForm = !showReplyForm}
                >
                  {t('reply')}
                </button>
              {/if}

              {#if onDelete}
                {#if confirmingAction === 'delete'}
                  <span class="threadkit-confirm-inline">
                    {t('deleteConfirm')}
                    <button
                      class="threadkit-confirm-btn threadkit-confirm-yes"
                      onclick={() => {
                        onDelete?.(comment.id);
                        confirmingAction = null;
                      }}
                    >
                      {t('yes')}
                    </button>
                    <button
                      class="threadkit-confirm-btn threadkit-confirm-no"
                      onclick={() => confirmingAction = null}
                    >
                      {t('no')}
                    </button>
                  </span>
                {:else}
                  <button
                    class="threadkit-action-btn"
                    onclick={() => confirmingAction = 'delete'}
                  >
                    {t('delete')}
                  </button>
                {/if}
              {/if}
            {:else}
              <!-- Other user's comment actions: block, report, reply, (mod: delete, ban) -->
              {#if currentUser && onBlock}
                {#if confirmingAction === 'block'}
                  <span class="threadkit-confirm-inline">
                    {t('blockConfirm')}
                    <button
                      class="threadkit-confirm-btn threadkit-confirm-yes"
                      onclick={() => {
                        onBlock?.(comment.userId);
                        confirmingAction = null;
                      }}
                    >
                      {t('yes')}
                    </button>
                    <button
                      class="threadkit-confirm-btn threadkit-confirm-no"
                      onclick={() => confirmingAction = null}
                    >
                      {t('no')}
                    </button>
                  </span>
                {:else}
                  <button
                    class="threadkit-action-btn"
                    onclick={() => confirmingAction = 'block'}
                  >
                    {t('block')}
                  </button>
                {/if}
              {/if}

              {#if currentUser && onReport}
                {#if reportSubmitted}
                  <span class="threadkit-report-thanks">{t('reportSubmitted')}</span>
                {:else if showReportForm}
                  <span class="threadkit-report-inline">
                    <select
                      class="threadkit-report-select"
                      bind:value={reportReason}
                    >
                      <option value="">{t('selectReason')}</option>
                      {#each REPORT_REASON_KEYS as reasonKey}
                        <option value={reasonKey}>{t(reasonKey)}</option>
                      {/each}
                    </select>
                    <button
                      class="threadkit-confirm-btn threadkit-confirm-yes"
                      disabled={!reportReason}
                      onclick={() => {
                        onReport?.(comment.id);
                        showReportForm = false;
                        reportSubmitted = true;
                      }}
                    >
                      {t('submit')}
                    </button>
                    <button
                      class="threadkit-confirm-btn threadkit-confirm-no"
                      onclick={() => {
                        showReportForm = false;
                        reportReason = '';
                      }}
                    >
                      {t('cancel')}
                    </button>
                  </span>
                {:else}
                  <button
                    class="threadkit-action-btn"
                    onclick={() => showReportForm = true}
                  >
                    {t('report')}
                  </button>
                {/if}
              {/if}

              {#if depth < maxDepth}
                <button
                  class="threadkit-action-btn"
                  onclick={() => showReplyForm = !showReplyForm}
                >
                  {t('reply')}
                </button>
              {/if}

              {#if isModOrAdmin && onDelete}
                {#if confirmingAction === 'delete'}
                  <span class="threadkit-confirm-inline">
                    {t('deleteConfirm')}
                    <button
                      class="threadkit-confirm-btn threadkit-confirm-yes"
                      onclick={() => {
                        onDelete?.(comment.id);
                        confirmingAction = null;
                      }}
                    >
                      {t('yes')}
                    </button>
                    <button
                      class="threadkit-confirm-btn threadkit-confirm-no"
                      onclick={() => confirmingAction = null}
                    >
                      {t('no')}
                    </button>
                  </span>
                {:else}
                  <button
                    class="threadkit-action-btn threadkit-mod-action"
                    onclick={() => confirmingAction = 'delete'}
                  >
                    {t('delete')}
                  </button>
                {/if}
              {/if}

              {#if isModOrAdmin && onBan}
                {#if confirmingAction === 'ban'}
                  <span class="threadkit-confirm-inline">
                    {t('banConfirm')}
                    <button
                      class="threadkit-confirm-btn threadkit-confirm-yes"
                      onclick={() => {
                        onBan?.(comment.userId);
                        confirmingAction = null;
                      }}
                    >
                      {t('yes')}
                    </button>
                    <button
                      class="threadkit-confirm-btn threadkit-confirm-no"
                      onclick={() => confirmingAction = null}
                    >
                      {t('no')}
                    </button>
                  </span>
                {:else}
                  <button
                    class="threadkit-action-btn threadkit-mod-action"
                    onclick={() => confirmingAction = 'ban'}
                  >
                    {t('ban')}
                  </button>
                {/if}
              {/if}
            {/if}
          </div>
        {/if}

        <!-- Reply form -->
        {#if showReplyForm}
          <div class="threadkit-reply-form">
            <CommentForm
              parentId={comment.id}
              placeholder={t('writeReply')}
              showCancel={true}
              onSubmit={async (text, parentId) => {
                handleReply();
              }}
              onCancel={handleFormCancel}
            />
          </div>
        {/if}

        <!-- Child comments -->
        {#if comment.children.length > 0}
          <div class="threadkit-replies">
            {#each comment.children as child, childIndex (child.id)}
              <Comment
                comment={child}
                {currentUser}
                depth={depth + 1}
                {maxDepth}
                index={childIndex}
                totalSiblings={comment.children.length}
                highlighted={highlightedCommentId === child.id}
                collapsed={collapsedThreads?.has(child.id)}
                {highlightedCommentId}
                {collapsedThreads}
                {onReply}
                {onVote}
                {onDelete}
                {onEdit}
                {onBan}
                {onBlock}
                {onReport}
                {onPermalink}
                {onCollapse}
                {getUserProfile}
                {plugins}
              />
            {/each}
          </div>
        {/if}
      </div>
    </div>
  </div>
{/if}
