// packages/react/src/components/NewCommentsBanner.tsx
import { useTranslation } from '../i18n';

interface NewCommentsBannerProps {
  count: number;
  onClick: () => void;
}

export function NewCommentsBanner({ count, onClick }: NewCommentsBannerProps) {
  const t = useTranslation();

  if (count === 0) return null;

  // Simple interpolation for the translation string
  const text = t('loadNewComments')
    .replace('{n}', String(count))
    .replace('{n, plural, one {comment} other {comments}}', count === 1 ? 'comment' : 'comments');

  return (
    <button
      className="threadkit-new-comments-banner"
      onClick={onClick}
      aria-live="polite"
      aria-atomic="true"
    >
      {text}
    </button>
  );
}

// packages/svelte/src/components/NewCommentsBanner.svelte
<script lang="ts">
  import { getTranslation } from '../i18n';

  const t = getTranslation();

  interface Props {
    count: number;
    onClick: () => void;
  }

  let { count, onClick }: Props = $props();

  // Simple interpolation for the translation string
  const text = $derived(
    t('loadNewComments')
      .replace('{n}', String(count))
      .replace('{n, plural, one {comment} other {comments}}', count === 1 ? 'comment' : 'comments')
  );
</script>

{#if count > 0}
  <button
    class="threadkit-new-comments-banner"
    onclick={onClick}
    aria-live="polite"
    aria-atomic="true"
  >
    {text}
  </button>
{/if}
